server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DiogoHumberto/spring-config-server/tree/master/configs/path
          searchPaths:
            - app-ratelimiter
            - app2

#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: c:\microservice-repo
