server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DiogoHumberto/spring-config-server
          searchPaths:
            - configs/path/app-ratelimiter
            - configs/path/app2
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: refresh


#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: c:\microservice-repo
